#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-87.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-88.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-89.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-90.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-91.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-92.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-93.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-94.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-95.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-96.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-97.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-98.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-99.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-100.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-101.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-102.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-103.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-104.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-105.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-106.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-107.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-108.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-109.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-110.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-111.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-112.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-113.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-114.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-115.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-116.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-117.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-118.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-119.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-120.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-121.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-122.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-123.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-124.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-125.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-126.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-127.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-128.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-129.json --cpus 16
