#!/bin/bash
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-0.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-105.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-110.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-115.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-120.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-125.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-130.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-135.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-140.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-15.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-145.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-150.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-155.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-160.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-165.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-170.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-20.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-25.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-30.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-35.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-40.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-5.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-45.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-50.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-55.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-60.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-65.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-70.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-75.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-80.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-85.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-90.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-10.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-95.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchRelu/DQN-Relu-goal-100.json --cpus 16
