#!/bin/bash
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-0.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-10.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-100.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-105.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-110.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-115.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-120.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-125.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-130.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-135.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-140.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-145.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-15.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-150.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-155.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-160.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-165.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-170.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-20.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-25.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-30.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-35.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-40.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-45.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-5.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-50.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-55.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-60.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-65.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-70.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-75.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-80.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-85.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-90.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/E1/P0//home/lolanff/rep-transfer/experiments/Gridworld/E1/P0/best-ScratchFTA/DQN-FTA-goal-95.json --cpus 16
