#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-129.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-130.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-131.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-132.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-133.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-134.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-135.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-136.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-137.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-138.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-139.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-140.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-141.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-142.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-143.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-144.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-145.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-146.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-147.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-148.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-149.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-150.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-151.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-152.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-153.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-154.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-155.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-156.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-157.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-158.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-159.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-160.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-161.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-162.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-163.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-164.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-165.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-166.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-167.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-168.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-169.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-170.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-171.json --cpus 16
