#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-86.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-87.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-88.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-89.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-90.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-91.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-92.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-93.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-94.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-95.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-96.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-97.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-98.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-99.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-100.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-101.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-102.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-103.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-104.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-105.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-106.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-107.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-108.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-109.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-110.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-111.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-112.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-113.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-114.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-115.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-116.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-117.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-118.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-119.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-120.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-121.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-122.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-123.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-124.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-125.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-126.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-127.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-128.json --cpus 16
