#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-0.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-1.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-2.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-3.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-4.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-5.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-6.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-7.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-8.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-9.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-10.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-11.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-12.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-13.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-14.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-15.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-16.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-17.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-18.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-19.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-20.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-21.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-22.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-23.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-24.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-25.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-26.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-27.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-28.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-29.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-30.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-31.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-32.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-33.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-34.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-35.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-36.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-37.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-38.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-39.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-40.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-41.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer-42.json --cpus 16
