#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer--1.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-0.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-1.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-2.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-3.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-4.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-5.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-6.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-7.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-8.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-9.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-10.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-11.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-12.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-13.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-14.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-15.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-16.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-17.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-18.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-19.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-20.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-21.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-22.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-23.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-24.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-25.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-26.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-27.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-28.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-29.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-30.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-31.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-32.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-33.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-34.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-35.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-36.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-37.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-38.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-39.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-40.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-41.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-42.json --cpus 16
