#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-43.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-44.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-45.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-46.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-47.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-48.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-49.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-50.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-51.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-52.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-53.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-54.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-55.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-56.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-57.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-58.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-59.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-60.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-61.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-62.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-63.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-64.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-65.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-66.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-67.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-68.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-69.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-70.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-71.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-72.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-73.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-74.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-75.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-76.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-77.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-78.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-79.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-80.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-81.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-82.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-83.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-84.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-85.json --cpus 16
python scripts/local.py --runs 5 -e experiments/Gridworld/A1/P1/transfer/DQN-ReLU-transfer-86.json --cpus 16
