#!/bin/bash
set -e
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-130.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-131.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-132.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-133.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-134.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-135.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-136.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-137.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-138.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-139.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-140.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-141.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-142.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-143.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-144.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-145.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-146.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-147.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-148.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-149.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-150.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-151.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-152.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-153.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-154.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-155.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-156.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-157.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-158.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-159.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-160.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-161.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-162.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-163.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-164.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-165.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-166.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-167.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-168.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-169.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-170.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-transfer-171.json --cpus 16
python scripts/local.py --runs 5 -e experiments/sparse_feature_scratch/transfer/DQN-ReLU-vf5-transfer--1.json --cpus 16
